#!/usr/bin/env node
try { require('dotenv').load(); } catch(err) { }//Do Nothin
const debug           = require('debug')('ysp:www');
const {createServer}  = require('http');
const bunyan          = require('bunyan');
const app             = require('./app/main');
const {normalizePort} = require('./lib');
const chalk           = require('chalk');

const PORT = process.env.PORT || 10000;
const server = createServer(app);

const show_banner = true;

var logger = bunyan.createLogger({name: 'YSP-API'});
function showBanner() {
  const banner = `
                    ===============================
                    √√     √√  (  ____ )  (  ____ )
                    √ √   √ √  | (     |  | (    )|
                     √ ©_© √   | (_____   | (____)|
                      √   √    (_____  )  |  _____)
                       √ √           ) |  | (
                       √ √     ||____) |  | )
                       √_√     |_______)  |/
                    ===============================
  `;
  console.log(chalk.green(banner));
}


/**
 * server start
 */
server.listen(normalizePort(PORT));
server.on('error', onError);
server.on('listening', onListen);


function onError(error) {
  if(error.syscall !== 'listen') throw error;
  var bind = typeof PORT === 'string'? 'Pipe' + PORT : 'Port' + PORT;
  switch (error.code){
    case 'EACCES':
      console.error(bind);
      process.exit(1);
    case 'EADDRINUSE':
      console.error(bind + 'is in USE');
      process.exit(1);
    default:
      throw error;
  }
}

function onListen() {
  if(show_banner) showBanner();
  console.log(process.env.DEBUG);
  debug('begin your show');
  logger.info('Start server at ' + server.address().port + ' port');
}
